"""Keywords (from "Grammar/python.gram")

This file is automatically generated; please don't muck it up!

To update the symbols in this file, 'cd' to the top directory of
the python source tree and run:

    PYTHONPATH=Tools/peg_generator python3 -m pegen.keywordgen \
        Grammar/python.gram \
        Grammar/Tokens \
        Lib/keyword.py

Alternatively, you can run 'make regen-keyword'.
"""

__all__ = ["iskeyword", "issoftkeyword", "kwlist", "softkwlist"]

kwlist = [
    'False',
    'None',
    'True',
    'and',
    'as',
    'assert',
    'async',
    'await',
    'break',
    'class',
    'continue',
    'def',
    'del',
    'elif',
    'else',
    'except',
    'finally',
    'for',
    'from',
    'global',
    'if',
    'import',
    'in',
    'is',
    'lambda',
    'nonlocal',
    'not',
    'or',
    'pass',
    'raise',
    'return',
    'try',
    'while',
    'with',
    'yield',
    '产出',
    '作为',
    '使用',
    '假值',
    '全局',
    '删除',
    '匿名函数',
    '否则',
    '否则如果',
    '如果',
    '定义',
    '对于',
    '导入',
    '尝试',
    '属于',
    '并且',
    '并非',
    '异步',
    '或者',
    '抛出',
    '捕获',
    '断言',
    '最终必须',
    '来自',
    '每当',
    '略过',
    '真值',
    '空值',
    '等同',
    '等待',
    '类型',
    '跳出',
    '跳过',
    '返回',
    '非局部'
]

softkwlist = [
    '_',
    'case',
    'match',
    'type',
    '匹配',
    '情形',
    '类型别名'
]

iskeyword = frozenset(kwlist).__contains__
issoftkeyword = frozenset(softkwlist).__contains__
