# -*- coding: utf-8 -*-
"""模块自带异常类的中文名（显示层用）。

由 `tools/生成模块异常名表.py` 从 `tools/提议模块异常名.py` 生成，**不要手改**。
方案与理由见 `docs/模块异常名方案.md`。

键是 `traceback` 会显示的那个名字（`模块.类名`），值是**只换类名那部分**的结果：

    "re.PatternError"              -> "模式错误"
    "json.decoder.JSONDecodeError" -> "JSON解码错误"

为什么留着模块前缀：中文名里有 13 组会撞车（`binascii.Error` / `_curses.error` /
`zlib.error` 全叫「错误」），去掉就分不出是谁报的了。模块名是代码记号，不动。

**只影响显示。** `type.__name__` / `__qualname__` / `__module__` 一个字没动，
所以 `pickle`、`inspect`、`except` 匹配、日志全都照旧。
`CHINESEPYTHON_ERRORS=en` 时这张表不生效。
"""

# 共 184 条
模块异常名 = {
    "FTP传输.Error":                                             "FTP传输.错误",
    "XML工具.dom.DOMException":                                  "XML工具.dom.DOM异常",
    "_csv.Error":                                              "_csv.错误",
    "_curses.error":                                           "_curses.错误",
    "_curses_panel.error":                                     "_curses_panel.错误",
    "_dbm.error":                                              "_dbm.错误",
    "_gdbm.error":                                             "_gdbm.错误",
    "_hashlib.UnsupportedDigestmodError":                      "_hashlib.不支持摘要算法错误",
    "_lzma.LZMAError":                                         "_lzma.LZMA错误",
    "_pickle.PickleError":                                     "_pickle.序列化错误",
    "_pickle.PicklingError":                                   "_pickle.序列化错误",
    "_pickle.UnpicklingError":                                 "_pickle.反序列化错误",
    "_py_warnings._OptionError":                               "_py_warnings.选项错误",
    "_pydecimal.DecimalException":                             "_pydecimal.十进制异常",
    "_pyrepl._module_completer.ParseError":                    "_pyrepl._module_completer.解析错误",
    "_pyrepl.keymap.KeySpecError":                             "_pyrepl.keymap.键规格错误",
    "_pyrepl.windows_console.WinError":                        "_pyrepl.windows_console.Windows错误",
    "_queue.Empty":                                            "_queue.空",
    "_tkinter.TclError":                                       "_tkinter.Tcl错误",
    "argparse.ArgumentError":                                  "argparse.参数错误",
    "argparse.ArgumentTypeError":                              "argparse.参数类型错误",
    "asyncio.exceptions.BrokenBarrierError":                   "asyncio.exceptions.屏障破裂错误",
    "asyncio.exceptions.CancelledError":                       "asyncio.exceptions.已取消错误",
    "asyncio.exceptions.IncompleteReadError":                  "asyncio.exceptions.不完整读错误",
    "asyncio.exceptions.InvalidStateError":                    "asyncio.exceptions.非法状态错误",
    "asyncio.exceptions.LimitOverrunError":                    "asyncio.exceptions.上限越界错误",
    "asyncio.exceptions.SendfileNotAvailableError":            "asyncio.exceptions.发送文件不可用错误",
    "asyncio.tools.CycleFoundException":                       "asyncio.tools.发现成环异常",
    "binascii.Error":                                          "binascii.错误",
    "binascii.Incomplete":                                     "binascii.不完整",
    "calendar.IllegalMonthError":                              "calendar.非法月错误",
    "calendar.IllegalWeekdayError":                            "calendar.非法星期错误",
    "compression.zstd.ZstdError":                              "compression.zstd.Zstd错误",
    "concurrent.futures._base.CancelledError":                 "concurrent.futures._base.已取消错误",
    "concurrent.futures._base.Error":                          "concurrent.futures._base.错误",
    "concurrent.futures._base.InvalidStateError":              "concurrent.futures._base.非法状态错误",
    "configparser.DuplicateOptionError":                       "configparser.重复选项错误",
    "configparser.DuplicateSectionError":                      "configparser.重复节错误",
    "configparser.Error":                                      "configparser.错误",
    "configparser.InterpolationDepthError":                    "configparser.插值深度错误",
    "configparser.InterpolationError":                         "configparser.插值错误",
    "configparser.InterpolationMissingOptionError":            "configparser.插值缺少选项错误",
    "configparser.InterpolationSyntaxError":                   "configparser.插值语法错误",
    "configparser.InvalidWriteError":                          "configparser.非法写错误",
    "configparser.MissingSectionHeaderError":                  "configparser.缺少节头错误",
    "configparser.MultilineContinuationError":                 "configparser.多行续行错误",
    "configparser.NoOptionError":                              "configparser.没有选项错误",
    "configparser.NoSectionError":                             "configparser.没有节错误",
    "configparser.ParsingError":                               "configparser.解析错误",
    "configparser.UnnamedSectionDisabledError":                "configparser.未命名节已停用错误",
    "copy.Error":                                              "copy.错误",
    "ctypes.ArgumentError":                                    "ctypes.参数错误",
    "dataclasses.FrozenInstanceError":                         "dataclasses.冻结实例错误",
    "decimal.DecimalException":                                "decimal.十进制异常",
    "doctest.UnexpectedException":                             "doctest.意料之外异常",
    "email._header_value_parser._InvalidEwError":              "email._header_value_parser.非法编码字错误",
    "email.errors.BoundaryError":                              "email.errors.边界错误",
    "email.errors.CharsetError":                               "email.errors.字符集错误",
    "email.errors.HeaderParseError":                           "email.errors.头解析错误",
    "email.errors.HeaderWriteError":                           "email.errors.头写错误",
    "email.errors.MessageError":                               "email.errors.消息错误",
    "email.errors.MessageParseError":                          "email.errors.消息解析错误",
    "email.errors.MultipartConversionError":                   "email.errors.多部分转换错误",
    "encodings.CodecRegistryError":                            "encodings.编解码器注册错误",
    "ftplib.Error":                                            "ftplib.错误",
    "getopt.GetoptError":                                      "getopt.选项解析错误",
    "getpass.GetPassWarning":                                  "getpass.口令警告",
    "graphlib.CycleError":                                     "graphlib.成环错误",
    "http.client.HTTPException":                               "http.client.HTTP异常",
    "http.cookiejar.LoadError":                                "http.cookiejar.加载错误",
    "http.cookies.CookieError":                                "http.cookies.Cookie错误",
    "idlelib.zoomheight.WmInfoGatheringError":                 "idlelib.zoomheight.窗口管理信息收集错误",
    "importlib._bootstrap._DeadlockError":                     "importlib._bootstrap.死锁错误",
    "importlib.metadata.PackageNotFoundError":                 "importlib.metadata.包未找到错误",
    "importlib.resources.abc.TraversalError":                  "importlib.resources.abc.遍历错误",
    "inspect.ClassFoundException":                             "inspect.发现类型异常",
    "ipaddress.AddressValueError":                             "ipaddress.地址值错误",
    "ipaddress.NetmaskValueError":                             "ipaddress.网络掩码值错误",
    "json.decoder.JSONDecodeError":                            "json.decoder.JSON解码错误",
    "locale.Error":                                            "locale.错误",
    "mailbox.Error":                                           "mailbox.错误",
    "mailbox.ExternalClashError":                              "mailbox.外部冲突错误",
    "mailbox.FormatError":                                     "mailbox.格式错误",
    "mailbox.NoSuchMailboxError":                              "mailbox.没有这个信箱错误",
    "mailbox.NotEmptyError":                                   "mailbox.非空错误",
    "multiprocessing.context.AuthenticationError":             "multiprocessing.context.认证错误",
    "multiprocessing.context.ProcessError":                    "multiprocessing.context.进程错误",
    "multiprocessing.context.TimeoutError":                    "multiprocessing.context.超时错误",
    "multiprocessing.managers.RemoteError":                    "multiprocessing.managers.远程错误",
    "multiprocessing.pool.MaybeEncodingError":                 "multiprocessing.pool.可能编码错误",
    "multiprocessing.resource_tracker.ReentrantCallError":     "multiprocessing.resource_tracker.可重入调用错误",
    "netrc.NetrcParseError":                                   "netrc.netrc解析错误",
    "optparse.AmbiguousOptionError":                           "optparse.有歧义选项错误",
    "optparse.BadOptionError":                                 "optparse.坏选项错误",
    "optparse.OptParseError":                                  "optparse.选项解析错误",
    "optparse.OptionConflictError":                            "optparse.选项冲突错误",
    "optparse.OptionError":                                    "optparse.选项错误",
    "optparse.OptionValueError":                               "optparse.选项值错误",
    "pickle.PickleError":                                      "pickle.序列化错误",
    "pickle.PicklingError":                                    "pickle.序列化错误",
    "pickle.UnpicklingError":                                  "pickle.反序列化错误",
    "plistlib.InvalidFileException":                           "plistlib.非法文件异常",
    "py_compile.PyCompileError":                               "py_compile.Py编译错误",
    "re.PatternError":                                         "re.模式错误",
    "runpy._Error":                                            "runpy.错误",
    "shutil.Error":                                            "shutil.错误",
    "shutil.ReadError":                                        "shutil.读错误",
    "shutil.RegistryError":                                    "shutil.注册错误",
    "shutil.SameFileError":                                    "shutil.同一个文件错误",
    "shutil.SpecialFileError":                                 "shutil.特殊文件错误",
    "signal.ItimerError":                                      "signal.间隔计时器错误",
    "smtplib.SMTPAuthenticationError":                         "smtplib.SMTP认证错误",
    "smtplib.SMTPConnectError":                                "smtplib.SMTP连接错误",
    "smtplib.SMTPDataError":                                   "smtplib.SMTP数据错误",
    "smtplib.SMTPException":                                   "smtplib.SMTP异常",
    "smtplib.SMTPHeloError":                                   "smtplib.SMTP问候错误",
    "smtplib.SMTPNotSupportedError":                           "smtplib.SMTP不支持错误",
    "smtplib.SMTPResponseException":                           "smtplib.SMTP响应异常",
    "socket._GiveupOnSendfile":                                "socket.放弃发送文件",
    "socket.gaierror":                                         "socket.地址信息错误",
    "socket.herror":                                           "socket.主机信息错误",
    "statistics.StatisticsError":                              "statistics.统计错误",
    "struct.error":                                            "struct.错误",
    "subprocess.CalledProcessError":                           "subprocess.被调用进程错误",
    "subprocess.SubprocessError":                              "subprocess.子进程错误",
    "tarfile.AbsoluteLinkError":                               "tarfile.绝对链接错误",
    "tarfile.AbsolutePathError":                               "tarfile.绝对路径错误",
    "tarfile.CompressionError":                                "tarfile.压缩错误",
    "tarfile.EOFHeaderError":                                  "tarfile.文件结束头错误",
    "tarfile.EmptyHeaderError":                                "tarfile.空头错误",
    "tarfile.ExtractError":                                    "tarfile.提取错误",
    "tarfile.FilterError":                                     "tarfile.筛选错误",
    "tarfile.HeaderError":                                     "tarfile.头错误",
    "tarfile.InvalidHeaderError":                              "tarfile.非法头错误",
    "tarfile.LinkFallbackError":                               "tarfile.链接回退错误",
    "tarfile.LinkOutsideDestinationError":                     "tarfile.链接指向目标之外错误",
    "tarfile.OutsideDestinationError":                         "tarfile.目标之外错误",
    "tarfile.ReadError":                                       "tarfile.读错误",
    "tarfile.SpecialFileError":                                "tarfile.特殊文件错误",
    "tarfile.StreamError":                                     "tarfile.流错误",
    "tarfile.SubsequentHeaderError":                           "tarfile.后续头错误",
    "tarfile.TarError":                                        "tarfile.Tar错误",
    "tarfile.TruncatedHeaderError":                            "tarfile.被截断头错误",
    "termios.error":                                           "termios.错误",
    "threading.BrokenBarrierError":                            "threading.屏障破裂错误",
    "tokenize.TokenError":                                     "tokenize.记号错误",
    "tomllib._parser.TOMLDecodeError":                         "tomllib._parser.TOML解码错误",
    "traceback.TracebackException":                            "traceback.回溯异常",
    "turtle.TurtleGraphicsError":                              "turtle.Turtle图形错误",
    "unittest.mock.InvalidSpecError":                          "unittest.mock.非法规格错误",
    "urllib.error.ContentTooShortError":                       "urllib.error.内容太短错误",
    "urllib.error.HTTPError":                                  "urllib.error.HTTP错误",
    "urllib.error.URLError":                                   "urllib.error.URL错误",
    "wave.Error":                                              "wave.错误",
    "webbrowser.Error":                                        "webbrowser.错误",
    "wsgiref.validate.WSGIWarning":                            "wsgiref.validate.WSGI警告",
    "xml.dom.DOMException":                                    "xml.dom.DOM异常",
    "xml.etree.ElementInclude.FatalIncludeError":              "xml.etree.ElementInclude.致命包含错误",
    "xml.etree.ElementInclude.LimitedRecursiveIncludeError":   "xml.etree.ElementInclude.受限递归包含错误",
    "xml.etree.ElementTree.ParseError":                        "xml.etree.ElementTree.解析错误",
    "xml.parsers.expat.ExpatError":                            "xml.parsers.expat.Expat错误",
    "xml.sax._exceptions.SAXException":                        "xml.sax._exceptions.SAX异常",
    "xml.sax._exceptions.SAXNotRecognizedException":           "xml.sax._exceptions.SAX 无法识别异常",
    "xml.sax._exceptions.SAXNotSupportedException":            "xml.sax._exceptions.SAX不支持异常",
    "xml.sax._exceptions.SAXParseException":                   "xml.sax._exceptions.SAX解析异常",
    "xmlrpc.client.Error":                                     "xmlrpc.client.错误",
    "xmlrpc.client.ProtocolError":                             "xmlrpc.client.协议错误",
    "xmlrpc.client.ResponseError":                             "xmlrpc.client.响应错误",
    "xx.error":                                                "xx.错误",
    "xxlimited.Error":                                         "xxlimited.错误",
    "xxlimited_35.error":                                      "xxlimited_35.错误",
    "zipapp.ZipAppError":                                      "zipapp.Zip应用错误",
    "zipimport.ZipImportError":                                "zipimport.Zip导入错误",
    "zlib.error":                                              "zlib.错误",
    "zoneinfo._common.ZoneInfoNotFoundError":                  "zoneinfo._common.时区未找到错误",
    "zoneinfo._tzpath.InvalidTZPathWarning":                   "zoneinfo._tzpath.非法时区路径警告",
    "单元测试.mock.InvalidSpecError":                              "单元测试.mock.非法规格错误",
    "多进程.context.TimeoutError":                                "多进程.context.超时错误",
    "海龟绘图.TurtleGraphicsError":                                "海龟绘图.Turtle图形错误",
    "电子邮件._邮件头值解析._InvalidEwError":                            "电子邮件._邮件头值解析.非法编码字错误",
    "腌制.PickleError":                                          "腌制.序列化错误",
    "腌制.PicklingError":                                        "腌制.序列化错误",
    "腌制.UnpicklingError":                                      "腌制.反序列化错误",
    "运行库._Error":                                              "运行库.错误",
}
