# -*- coding: utf-8 -*-
"""关键字工具 —— 汉语库（由 tools/汉化库.py 从 Lib/keyword.py 机械生成，**不要手改**）。

英文库 Lib/keyword.py 一个字节都没动。本文件分两段：
  第一段 深拷贝派生 —— 只改了名字，逻辑逐记号相同（生成时机器证明过）；
  第二段 英文原名转发层 —— 新加的，让英文原名和中文名指向**同一个对象**。

想改名字：改 tools/库词表.py，然后跑 tools/汉化库.py 关键字工具
"""


"""Keywords (from "Grammar/python.gram")

This file is automatically generated; please don't muck it up!

To update the symbols in this file, 'cd' to the top directory of
the python source tree and run:

    PYTHONPATH=Tools/peg_generator python3 -m pegen.keywordgen         Grammar/python.gram         Grammar/Tokens         Lib/keyword.py

Alternatively, you can run 'make regen-keyword'.
"""
_英文原名表 = {'iskeyword': '是关键字吗', 'issoftkeyword': '是软关键字吗', 'kwlist': '关键字表', 'softkwlist': '软关键字表'}

def __getattr__(名字):
    中 = _英文原名表.get(名字)
    if 中 is not None and 中 in globals():
        return globals()[中]
    raise AttributeError(名字)
__all__ = ['iskeyword', 'issoftkeyword', 'kwlist', 'softkwlist']
关键字表 = ['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield', '产出', '作为', '使用', '假值', '全局', '删除', '匿名函数', '否则', '否则如果', '如果', '定义', '对于', '导入', '尝试', '属于', '并且', '并非', '异步', '或者', '抛出', '捕获', '断言', '最终必须', '来自', '每当', '略过', '真值', '空值', '等同', '等待', '类型', '跳出', '跳过', '返回', '非局部']
软关键字表 = ['_', 'case', 'match', 'type', '匹配', '情形', '类型别名']
是关键字吗 = frozenset(关键字表).__contains__
是软关键字吗 = frozenset(软关键字表).__contains__


# ============================================================================
# 英文原名转发层（照 D-024）——「同一对象两种名字」
#
# 这一段是**新加的**，不在「只改名字」的等价证明范围内。
#   * 模块级、类成员：静态别名，指向的是**同一个对象**；
#   * 实例属性：类上挂 __getattr__/__setattr__，把英文名翻成中文名。
# 有了这一层，官方自带的测试可以原样跑在本模块上（换掉 sys.modules 即可）。
# ============================================================================
_模块别名 = {
    'iskeyword': '是关键字吗',
    'issoftkeyword': '是软关键字吗',
    'kwlist': '关键字表',
    'softkwlist': '软关键字表',
}
globals().update({_英: globals()[_中]
                   for _英, _中 in _模块别名.items()
                   if _中 in globals()})

# __all__：英文原名一个都不能少（硬约束），中文名并排加在后面。
__all__ = type(__all__)(list(__all__) + [
    '关键字表',
    '是关键字吗',
    '是软关键字吗',
    '软关键字表',
])

# ---- 转发层结束 ----
