// 自动生成，别手改。来源：Lib/zh_errmessages*.py
// 重新生成：python tools/生成C层报错表.py --写出
//
// ChinesePython：unraisable 第一行正文的中英对照。
// unraisable 走 Python/errors.c 的 write_unraisable_exc_file()，完全在 C 里，
// 够不着 Lib/traceback.py 那张 Python 表，所以这里给它一张 C 能直接用的。
//
// 每条只有**一段**占位符（或没有），所以「英文前缀 + 中间 + 英文后缀」
// 唯一确定一条，重写成「中文前缀 + 中间 + 中文后缀」——中间那段是占位符
// 渲染出来的值，原样搬过去。中文语序和英文不同，靠前后缀调换。
//
// 表按英文前缀从长到短排：C 那边取第一个命中的，更具体的先赢。

#ifndef Py_INTERNAL_ZH_UNRAISABLE_H
#define Py_INTERNAL_ZH_UNRAISABLE_H

#ifdef __cplusplus
extern "C" {
#endif

#ifndef Py_BUILD_CORE
#  error "this header requires Py_BUILD_CORE define"
#endif

// 共 99 条（另有 5 条占位符太多，留给英文兜底）
typedef struct {
    const char *en_pre;
    const char *en_suf;
    const char *zh_pre;
    const char *zh_suf;
} _Py_zh_unraisable;

static const _Py_zh_unraisable _Py_zh_unraisable_table[] = {
    {"Exception ignored in PyMapping_HasKeyString(); consider using PyMapping_HasKeyStringWithError(), PyMapping_GetOptionalItemString() or PyMapping_GetItemString()", "",
     "PyMapping_HasKeyString() 中的异常被忽略；请考虑改用 PyMapping_HasKeyStringWithError()、PyMapping_GetOptionalItemString() 或 PyMapping_GetItemString()", ""},
    {"Exception ignored in PyObject_HasAttrString(); consider using PyObject_HasAttrStringWithError(), PyObject_GetOptionalAttrString() or PyObject_GetAttrString()", "",
     "PyObject_HasAttrString() 中忽略了异常；考虑改用 PyObject_HasAttrStringWithError()、PyObject_GetOptionalAttrString() 或 PyObject_GetAttrString()", ""},
    {"Exception ignored in PyMapping_HasKey(); consider using PyMapping_HasKeyWithError(), PyMapping_GetOptionalItem() or PyObject_GetItem()", "",
     "PyMapping_HasKey() 中的异常被忽略；请考虑改用 PyMapping_HasKeyWithError()、PyMapping_GetOptionalItem() 或 PyObject_GetItem()", ""},
    {"Exception ignored in PyObject_HasAttr(); consider using PyObject_HasAttrWithError(), PyObject_GetOptionalAttr() or PyObject_GetAttr()", "",
     "PyObject_HasAttr() 中忽略了异常；考虑改用 PyObject_HasAttrWithError()、PyObject_GetOptionalAttr() 或 PyObject_GetAttr()", ""},
    {"Exception ignored in PyDict_GetItemString(); consider using PyDict_GetItemStringRef()", "",
     "PyDict_GetItemString() 中的异常被忽略；考虑改用 PyDict_GetItemStringRef()", ""},
    {"Exception ignored in ssl servername callback while calling set SNI callback (result=", ")",
     "在 ssl 服务器名回调中调用 set SNI 回调时忽略了异常（结果=", "）"},
    {"Exception ignored in ssl servername callback while calling set SNI callback ", "",
     "在 ssl 服务器名回调中调用 set SNI 回调 ", " 时忽略了异常"},
    {"Exception ignored while converting result of ctypes callback function ", "",
     "转换 ctypes 回调函数 ", " 的结果时忽略了异常"},
    {"Exception ignored in ssl PSK client callback while calling callback ", "",
     "在 ssl PSK 客户端回调中调用回调 ", " 时忽略了异常"},
    {"Exception ignored in ssl PSK server callback while calling callback ", "",
     "在 ssl PSK 服务器回调中调用回调 ", " 时忽略了异常"},
    {"Exception ignored while setting error for ctypes callback function ", "",
     "为 ctypes 回调函数 ", " 设置错误时忽略了异常"},
    {"Exception ignored in ssl servername callback while decoding name ", "",
     "在 ssl 服务器名回调中解码名字 ", " 时忽略了异常"},
    {"Exception ignored while joining a thread in _thread._shutdown()", "",
     "在 _thread._shutdown() 中加入线程时忽略了异常", ""},
    {"Exception ignored while trying to write to the signal wakeup fd", "",
     "尝试写入信号唤醒 fd 时忽略了异常", ""},
    {"Exception ignored while trying to send to the signal wakeup fd", "",
     "尝试发送到信号唤醒 fd 时忽略了异常", ""},
    {"Exception ignored while appending nested instruction sequence", "",
     "追加嵌套指令序列时忽略了异常", ""},
    {"Exception ignored while removing the last compiler stack item", "",
     "移除最后一个编译器栈项时忽略了异常", ""},
    {"Exception ignored while deallocating overlapped operation ", "",
     "释放重叠操作 ", " 时忽略了异常"},
    {"Exception ignored in GC shutdown while formatting garbage", "",
     "GC 关闭时格式化垃圾时忽略了异常", ""},
    {"Exception ignored while calling ctypes callback function ", "",
     "调用 ctypes 回调函数 ", " 时忽略了异常"},
    {"Exception ignored while calling ctypes traverse function ", "",
     "调用 ctypes 遍历函数 ", " 时忽略了异常"},
    {"Exception ignored while clearing interpreters module list", "",
     "清除解释器模块列表时忽略了异常", ""},
    {"Exception ignored in atfork callback while copying list ", "",
     "复制列表 ", " 时 atfork 回调中的异常被忽略"},
    {"Exception ignored while calling ctypes.DllGetClassObject", "",
     "调用 ctypes.DllGetClassObject 时忽略了异常", ""},
    {"Exception ignored while clearing sys.path_importer_cache", "",
     "清除 sys.path_importer_cache 时忽略了异常", ""},
    {"Exception ignored while clearing an object managed dict", "",
     "清理对象的托管字典时忽略了异常", ""},
    {"Exception ignored while finalizing database connection ", "",
     "收尾数据库连接 ", " 时忽略了异常"},
    {"Exception ignored while propagating not shareable error", "",
     "传播不可共享错误时忽略了异常", ""},
    {"Exception ignored while calling ctypes.DllCanUnloadNow", "",
     "调用 ctypes.DllCanUnloadNow 时忽略了异常", ""},
    {"Exception ignored while discarding thread watchdog of ", "",
     "丢弃 ", " 的线程看门狗时忽略了异常"},
    {"Exception ignored in the internal traceback machinery", "",
     "内部回溯机制中忽略了异常", ""},
    {"Exception ignored while formatting TracebackException", "",
     "格式化 TracebackException 时忽略了异常", ""},
    {"Exception ignored while finalizing a Tcl interpreter", "",
     "终结 Tcl 解释器时忽略了异常", ""},
    {"Exception ignored while finalizing scandir iterator ", "",
     "终结 scandir 迭代器 ", " 时忽略了异常"},
    {"Exception ignored while removing an interned string ", "",
     "移除驻留字符串 ", " 时忽略了异常"},
    {"Exception ignored while calling _ctypes.DictRemover", "",
     "调用 _ctypes.DictRemover 时忽略了异常", ""},
    {"Exception ignored while capturing preserved objects", "",
     "捕获保留对象时忽略了异常", ""},
    {"Exception ignored while creating TracebackException", "",
     "创建 TracebackException 时忽略了异常", ""},
    {"Exception ignored while destroying _lsprof profiler", "",
     "销毁 _lsprof profiler 时忽略了异常", ""},
    {"Exception ignored while finalizing async generator ", "",
     "收尾异步生成器 ", " 时忽略了异常"},
    {"Exception ignored while destroying pyexact capsule", "",
     "销毁 pyexact 胶囊时忽略了异常", ""},
    {"Exception ignored while setting builtin variable _", "",
     "设置内置变量 _ 时忽略了异常", ""},
    {"Exception ignored while calling asyncio function ", "",
     "调用 asyncio 函数 ", " 时忽略了异常"},
    {"Exception ignored while calling weakref callback ", "",
     "调用弱引用回调 ", " 时忽略了异常"},
    {"Exception ignored while clearing _datetime module", "",
     "清理 _datetime 模块时忽略了异常", ""},
    {"Exception ignored while deleting thread local of ", "",
     "删除 ", " 的线程本地数据时忽略了异常"},
    {"Exception ignored in PyEval_SetProfileAllThreads", "",
     "PyEval_SetProfileAllThreads 中的异常被忽略", ""},
    {"Exception ignored while clearing object weakrefs", "",
     "清理对象弱引用时忽略了异常", ""},
    {"Exception ignored while copying atexit callbacks", "",
     "复制 atexit 回调时忽略了异常", ""},
    {"Exception ignored while clearing sys.path_hooks", "",
     "清除 sys.path_hooks 时忽略了异常", ""},
    {"Exception ignored while reading getpath results", "",
     "读取 getpath 结果时忽略了异常", ""},
    {"Exception ignored in PyEval_SetTraceAllThreads", "",
     "PyEval_SetTraceAllThreads 中的异常被忽略", ""},
    {"Exception ignored on calling weakref callback ", "",
     "调用弱引用回调 ", " 时忽略了异常"},
    {"Exception ignored while calling _lsprof timer ", "",
     "调用 _lsprof 计时器 ", " 时忽略了异常"},
    {"Exception ignored while calling signal handler", "",
     "调用信号处理器时忽略了异常", ""},
    {"Exception ignored while clearing sys.meta_path", "",
     "清除 sys.meta_path 时忽略了异常", ""},
    {"Exception ignored while clearing thread local ", "",
     "清理线程局部对象 ", " 时忽略了异常"},
    {"Exception ignored while finalizing coroutine ", "",
     "终结协程 ", " 时忽略了异常"},
    {"Exception ignored while finalizing generator ", "",
     "终结生成器 ", " 时忽略了异常"},
    {"Exception ignored while invoking gc callbacks", "",
     "调用 gc 回调时忽略了异常", ""},
    {"Exception ignored in PyCursesPanel_Dealloc()", "",
     "在 PyCursesPanel_Dealloc() 中忽略了异常", ""},
    {"Exception ignored in ssl servername callback", "",
     "在 ssl 服务器名回调中被忽略的异常", ""},
    {"Exception ignored while calling GC callback ", "",
     "调用 GC 回调 ", " 时忽略了异常"},
    {"Exception ignored while calling deallocator ", "",
     "调用 ", " 的析构函数时忽略了异常"},
    {"Exception ignored while clearing module dict", "",
     "清空模块字典时忽略了异常", ""},
    {"Exception ignored while clearing sys.modules", "",
     "清空 sys.modules 时忽略了异常", ""},
    {"Exception ignored while deallocating ctypes ", "",
     "释放 ctypes ", " 时忽略了异常"},
    {"Exception ignored in __release_buffer__ of ", "",
     "", " 的 __release_buffer__ 中忽略了异常"},
    {"Exception ignored while flushing sys.stdout", "",
     "刷新 sys.stdout 时忽略了异常", ""},
    {"Exception ignored while setting _errdisplay", "",
     "设置 _errdisplay 时忽略了异常", ""},
    {"Exception ignored on invoking gc callbacks", "",
     "调用 gc 回调时忽略了异常", ""},
    {"Exception ignored while closing generator ", "",
     "关闭生成器 ", " 时忽略了异常"},
    {"Exception ignored while finalizing socket ", "",
     "终结套接字 ", " 时忽略了异常"},
    {"Exception ignored while freeing JIT memory", "",
     "释放 JIT 内存时忽略了异常", ""},
    {"Exception ignored while restoring __main__", "",
     "恢复 __main__ 时忽略了异常", ""},
    {"Exception ignored while restoring builtins", "",
     "恢复 builtins 时忽略了异常", ""},
    {"Exception ignored in bf_releasebuffer of ", "",
     "", " 的 bf_releasebuffer 里忽略了异常"},
    {"Exception ignored while closing database ", "",
     "关闭数据库 ", " 时忽略了异常"},
    {"Exception ignored while preparing getpath", "",
     "准备 getpath 时忽略了异常", ""},
    {"Exception ignored on object deallocation", "",
     "释放对象时忽略了异常", ""},
    {"Exception ignored while clearing ctypes ", "",
     "清理 ctypes ", " 时忽略了异常"},
    {"Exception ignored while finalizing file ", "",
     "终结文件 ", " 时忽略了异常"},
    {"Exception ignored while removing modules", "",
     "移除模块时忽略了异常", ""},
    {"Exception ignored in garbage collection", "",
     "垃圾回收中忽略了异常", ""},
    {"Exception ignored in thread started by ", "",
     "在由 ", " 启动的线程中被忽略的异常"},
    {"Exception ignored on threading shutdown", "",
     "threading 关闭时忽略了异常", ""},
    {"Exception ignored while running getpath", "",
     "运行 getpath 时忽略了异常", ""},
    {"Exception ignored in PyEval_SetProfile", "",
     "PyEval_SetProfile 中的异常被忽略", ""},
    {"Exception ignored in PySys_GetObject()", "",
     "PySys_GetObject() 中忽略了异常", ""},
    {"Exception ignored in m_clear of module", "%V",
     "忽略了模块", " 的 m_clear 中的异常"},
    {"Exception ignored on sqlite3 callback ", "",
     "sqlite3 回调 ", " 上忽略了异常"},
    {"Exception ignored while restoring sys.", "",
     "恢复 sys.", " 时忽略了异常"},
    {"Exception ignored in atexit callback ", "",
     "在 atexit 回调 ", " 中忽略了异常"},
    {"Exception ignored in atfork callback ", "",
     "atfork 回调 ", " 中的异常被忽略"},
    {"Exception ignored while clearing sys.", "",
     "清理 sys.", " 时忽略了异常"},
    {"Exception ignored in PyEval_SetTrace", "",
     "PyEval_SetTrace 中的异常被忽略", ""},
    {"Exception ignored in tp_clear of ", "",
     "在 ", " 的 tp_clear 中忽略了异常"},
    {"Exception ignored in GC shutdown", "",
     "GC 关闭时忽略了异常", ""},
    {"Exception ignored in audit hook", "",
     "审计钩子中忽略了异常", ""},
};

#ifdef __cplusplus
}
#endif
#endif /* !Py_INTERNAL_ZH_UNRAISABLE_H */
